-- ALTERANDO DADOS DE UM REGISTRO
/*

SINTAXE: 

UPDATE <NOME DA TABELA>
SET <COLUNA1> = <NOVO VALOR>,
  <COLUNA2> = <NOVO VALOR>,
  <COLUNA3> = <NOVO VALOR>
WHERE <CONDICAO LOGICA>;


*/

UPDATE PESSOA
SET NOME = 'DARTH VADER',
	DATA_NASCIMENTO = '1994-05-01',
    DATA_CADASTRO = '2013-11-04'
WHERE CODIGO = 30;

